### PR TITLE
Fix nasty 500 error on POST to /_config

### PR DESCRIPTION
**Pull request by wenli200133**
## Overview

When the ini config file is read only,  function of 
`file:write_file(File, NewFileContents).` doesn't return `ok`, so for here we should handle the return error scenario. 

## Testing recommendations

```
wenwl@wenwl_mbp:~/cloudant/couchdb$ chmod a-w ./dev/lib/node1/etc/local.ini
wenwl@wenwl_mbp:~/cloudant/couchdb$ curl -X PUT localhost:15984/_node/_local/_config/admins/joan1 -d '"500"' -u adm:pass
{"error":"bad_request","reason":"eacces"}
wenwl@wenwl_mbp:~/cloudant/couchdb$ curl -X DELETE localhost:15984/_node/_local/_config/admins/joan1 -u adm:pass
{"error":"bad_request","reason":"eacces"}
```

## Related Issues or Pull Requests

This PR and https://github.com/apache/couchdb/pull/1717  is for fixing issue of https://github.com/apache/couchdb/issues/1380
PR https://github.com/apache/couchdb/pull/1717 is dependent on this.
so this PR should be first merged into master, then https://github.com/apache/couchdb/pull/1717 can pick it up.

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by jiangphcn** [comment]
+1 looks good from my side. CI should be fine when https://github.com/apache/couchdb-config/pull/22 is merged.
@wohali, hey Joan, would you please help take a look?

**Comment by jiangphcn** [comment]
I will merge this PR if there is no additional comments. @wohali

**Comment by wohali** [comment]
You're the one who gave it a +1 @jiangphcn ;) I'm not reviewing the code here, just helping you with the process!

**Comment by jiangphcn** [comment]
@wohali thanks for your help on process. Just merged

**Pull request merged**
