### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by bessbd**

### CODE REVIEW

**Comment by wohali** [comment]
@bessbd FYI if you're fixing CI and you're not doing a major change, it's acceptable to not need a +1.

But here's a +1 for you anyway if this fixes it 😉

**Comment by bessbd** [comment]
Hi @wohali ,

I have no idea whether this fixes it or not. I just wanted to see if it's really a (hopefully a) singe-line change. (Hence the `draft`.)

Thank you for the review and +1 though!

Also, I wasn't sure this is the right course of action - going for `3.x` in `couchdb` or if we should figure out the fdb issue fix here.

**Comment by mtenrero** [comment]
The current CI issue can be solved with this PR[https://github.com/apache/couchdb-config/pull/33](https://github.com/apache/couchdb-config/pull/33)

**Comment by bessbd** [comment]
Good call, thank you for that @mtenrero .

Still, I think we should do a version of this change as well so that we have better confidence of `couchdb-config`'s CouchDB 3.x compatibility.

I'll push a commit here to enable matrix builds (3.x and `main`) and to remove erlang 19 support ( https://lists.apache.org/thread.html/r82bf3ef66fe359a3ff72d8a9f9cf3a97918a867129b1aab3fa4d1f41%40%3Cdev.couchdb.apache.org%3E )

**Comment by bessbd** [comment]
Thank you all for the collaboration on this. I'm about to merge the PR.

**Pull request merged**
